# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("add_one works", {
  expect_equal(add_one(12), 13)
  expect_equal(add_one(56), 57)
})
